project:
  type: website

website:
  title: "Tobias Vlćek"
  search: false
  page-footer: "2025, Tobias Vlćek" 
  navbar:
    left:
      - href: index.qmd
        text: About me 

format:
  html:
    theme: 
    - litera
    - styles.scss
    include-in-header:
    - header.html