project:
  type: website

website:
  title: "Tobias Vlćek"
  search: false
  page-footer: "2025, Tobias Vlćek"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: lectures.qmd
        text: Lectures

format:
  html:
    theme:
      - default
      - brand
    include-in-header:
      - header.html
