project:
  type: website

website:
  title: "Tobias Vlćek"
  search: false
  page-footer:
    center: "2025, Tobias Vlćek"
    right:
      - icon: imprint
        href: imprint.qmd
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: lectures.qmd
        text: Lectures
      - href: research.qmd
        text: Research

format:
  html:
    theme:
      - default
      - brand
    include-in-header:
      - header.html
